/**
 * useAlertRuleMutation.ts
 *
 * React hook for persisting alert rule definitions.
 * Supports both traditional form-based rules and script-based rules
 * authored in the Monaco Script Playground.
 *
 * Uses TanStack Query's useMutation for optimistic updates,
 * automatic retries, and cache invalidation.
 */

'use client';

import { useMutation, useQueryClient } from '@tanstack/react-query';

// ─── Types ────────────────────────────────────────────────────────────────────

export type AlertRuleType = 'threshold' | 'script';

export interface ThresholdRuleConfig {
  type: 'threshold';
  metric: string;
  operator: 'gt' | 'gte' | 'lt' | 'lte' | 'eq';
  value: number;
  windowMinutes: number;
}

export interface ScriptRuleConfig {
  type: 'script';
  code: string;
}

export type AlertRuleConfig = ThresholdRuleConfig | ScriptRuleConfig;

export interface AlertRuleDefinition {
  /** Unique rule identifier (generated by the backend). */
  id?: string;
  /** Human-readable name for the rule. */
  name: string;
  /** Description of what this rule monitors. */
  description: string;
  /** Whether the rule is actively evaluated. */
  enabled: boolean;
  /** Severity level when the rule triggers. */
  severity: 'critical' | 'warning' | 'info';
  /** The rule configuration — either a threshold definition or a script. */
  config: AlertRuleConfig;
  /** ISO timestamp of last modification. */
  updatedAt?: string;
}

// ─── API layer (stub — replace with real API calls) ───────────────────────────

const ALERT_RULES_QUERY_KEY = ['alert-rules'] as const;

async function saveAlertRule(
  rule: AlertRuleDefinition
): Promise<AlertRuleDefinition> {
  // In a real implementation this would call the backend API.
  // For now we simulate a network round-trip.
  await new Promise((resolve) => setTimeout(resolve, 300));

  return {
    ...rule,
    id: rule.id ?? crypto.randomUUID(),
    updatedAt: new Date().toISOString(),
  };
}

async function deleteAlertRule(ruleId: string): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, 200));
  void ruleId;
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

export function useAlertRuleMutation() {
  const queryClient = useQueryClient();

  const saveMutation = useMutation({
    mutationFn: saveAlertRule,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ALERT_RULES_QUERY_KEY });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: deleteAlertRule,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ALERT_RULES_QUERY_KEY });
    },
  });

  return {
    /** Save (create or update) an alert rule. */
    saveRule: saveMutation.mutate,
    saveRuleAsync: saveMutation.mutateAsync,
    isSaving: saveMutation.isPending,
    saveError: saveMutation.error,

    /** Delete an alert rule by ID. */
    deleteRule: deleteMutation.mutate,
    isDeleting: deleteMutation.isPending,
    deleteError: deleteMutation.error,
  } as const;
}
